### PR TITLE
Add Fixes

### LINKED ISSUE #101: Lingo.Ai icon not redirecting to Home Page
The Lingo.ai icon doesn't redirect to home page

https://github.com/user-attachments/assets/fbb0d8ce-b641-4452-8c2c-bc489bba7ac5

### LINKED ISSUE #118: Colour code and Error message handling on Login form
**Steps to Reproduce** 
Open the Sign In page. 
Test each scenario below and press Sign In after entering data: 
o Leave Email blank. 
o Type an invalid e-mail such as test@. 
o Leave Password blank. 
o Enter a password shorter than 8 characters. 
o Submit a valid-format email with the wrong password.

**Actual Result** 
• Same generic messages (“Invalid email”, “Password must be at least 8 characters long”) 
appear for several error states. 
• Field labels and error messages both turn red, so corrected fields still look wrong. 
• Input borders stay the normal colour, giving no clear visual cue.

**Expected Result** 
1. 

Image

**Constant (Neutral) Colours** 
• Labels, placeholders, helper copy: black (never changes). 
• Error state: use red only for the input border and the error message—not for the label.

### PR DESCRIPTION
**Pull request by shadabb-josh**
- Added proper messages and removed the generic one's. fixed the UI and enabled logo to navigate back to home.
- Before 
Screenshot from 2025-07-14 12-03-30
Screenshot from 2025-07-14 12-03-50

- After
image
Screenshot from 2025-07-14 12-04-16

Fixes #118 , #101 
 <div id='description'>
    <a href="https://bito.ai#summarystart"></a>
<h3>Summary by Bito</h3>
This pull request enhances form handling, validation, and navigation functionalities by removing unnecessary imports and improving UI behavior. It refines error messages for consistent user experience, introduces better error handling mechanisms, and fixes logo navigation to the home page. These changes streamline the overall form handling and validation processes.

</div>

### CODE REVIEW

File: app/src/Validators/register.ts [hunk 1]
```diff
@@ -1,33 +1,30 @@
...
-  }),
-  userName: z.string().min(2, {
-    message: "Name should be atleast 2 characters long"
-  }),
-  contact: z.string().regex(/^\d{10}$/, {
-    message: "Contact number must be exactly 10 digits"
-  })
-
+  userEmail: z.string()
+    .min(1, { message: "Email is required" })
```
Comment (sourabh-josh) [inline app/src/Validators/register.ts]: Please add the validation messages to a constants file 
so they can be reused elsewhere

File: app/src/components/UserForm.tsx [hunk 2]
```diff
@@ -32,7 +32,7 @@ const UserForm = (props: UserFormProps) => {
   const form = useForm<SignupUserRequest | SigninUserRequest>({
     resolver: zodResolver(isSignup ? signupUserSchema : signinUserSchema),
     defaultValues: isSignup ? { password: "", userEmail: "", userName: "", contact: "" } : { password: "", userEmail: "" },
-    mode: "all",
+    mode: "onChange",
```
Comment (sourabh-josh) [inline app/src/components/UserForm.tsx]: I suggest we keep the form validation mode set to "all" instead of just "onChange".

For example, if a user clicks into the email field and then moves to the password field without entering any value, the form won’t show any validation message until they click the submit button.

While it’s a small detail, I believe using "all" provides slightly better UX by offering immediate feedback across interactions.

File: app/src/components/ui/form.tsx [hunk 3]
```diff
@@ -95,7 +95,7 @@ const FormLabel = React.forwardRef<
   return (
     <Label
       ref={ref}
-      className={cn(error && "text-destructive", className)}
```
Comment (sourabh-josh) [inline app/src/components/ui/form.tsx]: I don’t think we need to modify the base ui components since it’s meant to be a generic base.
If you want to change the behavior, it’s better to handle it at the usage level instead.

File: app/src/components/ui/form.tsx [hunk 4]
```diff
@@ -158,7 +158,7 @@ const FormMessage = React.forwardRef<
     <p
       ref={ref}
       id={formMessageId}
-      className={cn("text-[0.8rem] font-medium text-destructive", className)}
```
Comment (sourabh-josh) [inline app/src/components/ui/form.tsx]: Please avoid directly overriding the styles of the form component.
If you’re trying to change the text color, it’s better to do it via custom css classes or update it in the Tailwind config instead.

**Review by sourabh-josh — CHANGES_REQUESTED** [review]

File: app/src/Validators/register.ts (hunk 1 above)
Comment (shadabb-josh) [reply app/src/Validators/register.ts]: Yes, extracted it.

File: app/src/components/ui/form.tsx (hunk 3 above)
Comment (shadabb-josh) [reply app/src/components/ui/form.tsx]: Yes, you're right.

File: app/src/components/ui/form.tsx (hunk 4 above)
Comment (shadabb-josh) [reply app/src/components/ui/form.tsx]: Yes.

File: app/src/components/Navigation.tsx [hunk 5]
```diff
@@ -32,6 +32,7 @@ import axios from "axios";
 import { Modal } from "./ui/modal";
 import ProfileInformation from "./ProfileInformation";
 import { supportEmail } from "@/constants/homePage";
+import { useRef, useCallback } from "react";
```
Comment (sourabh-josh) [inline app/src/components/Navigation.tsx]: if we are not using these hooks please remove the imports

**Review by sourabh-josh — CHANGES_REQUESTED** [review]

**Review by sourabh-josh — APPROVED** [review]
